# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bot.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import bot_comm_pb2 as bot__comm__pb2
import transaction_pb2 as transaction__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='bot.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tbot.proto\x1a\x0e\x62ot_comm.proto\x1a\x11transaction.proto2\xc7\x02\n\x0f\x42otCommunicator\x12(\n\tRemoveBot\x12\x0b.BotRequest\x1a\x0c.BotResponse\"\x00\x12(\n\tResumeBot\x12\x0b.BotRequest\x1a\x0c.BotResponse\"\x00\x12\'\n\x08PauseBot\x12\x0b.BotRequest\x1a\x0c.BotResponse\"\x00\x12&\n\x07StopBot\x12\x0b.BotRequest\x1a\x0c.BotResponse\"\x00\x12#\n\x04Ping\x12\x0b.BotRequest\x1a\x0c.BotResponse\"\x00\x12\x39\n\x19ResponseForRequestedTrade\x12\x0c.Transaction\x1a\x0c.BotResponse\"\x00\x12/\n\x0eSendOpenTrades\x12\r.Transactions\x1a\x0c.BotResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[bot__comm__pb2.DESCRIPTOR,transaction__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_BOTCOMMUNICATOR = _descriptor.ServiceDescriptor(
  name='BotCommunicator',
  full_name='BotCommunicator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=49,
  serialized_end=376,
  methods=[
  _descriptor.MethodDescriptor(
    name='RemoveBot',
    full_name='BotCommunicator.RemoveBot',
    index=0,
    containing_service=None,
    input_type=bot__comm__pb2._BOTREQUEST,
    output_type=bot__comm__pb2._BOTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ResumeBot',
    full_name='BotCommunicator.ResumeBot',
    index=1,
    containing_service=None,
    input_type=bot__comm__pb2._BOTREQUEST,
    output_type=bot__comm__pb2._BOTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='PauseBot',
    full_name='BotCommunicator.PauseBot',
    index=2,
    containing_service=None,
    input_type=bot__comm__pb2._BOTREQUEST,
    output_type=bot__comm__pb2._BOTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StopBot',
    full_name='BotCommunicator.StopBot',
    index=3,
    containing_service=None,
    input_type=bot__comm__pb2._BOTREQUEST,
    output_type=bot__comm__pb2._BOTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Ping',
    full_name='BotCommunicator.Ping',
    index=4,
    containing_service=None,
    input_type=bot__comm__pb2._BOTREQUEST,
    output_type=bot__comm__pb2._BOTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ResponseForRequestedTrade',
    full_name='BotCommunicator.ResponseForRequestedTrade',
    index=5,
    containing_service=None,
    input_type=transaction__pb2._TRANSACTION,
    output_type=bot__comm__pb2._BOTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SendOpenTrades',
    full_name='BotCommunicator.SendOpenTrades',
    index=6,
    containing_service=None,
    input_type=transaction__pb2._TRANSACTIONS,
    output_type=bot__comm__pb2._BOTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BOTCOMMUNICATOR)

DESCRIPTOR.services_by_name['BotCommunicator'] = _BOTCOMMUNICATOR

# @@protoc_insertion_point(module_scope)
