# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bot_comm.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bot_comm.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x62ot_comm.proto\"\x07\n\x05\x45mpty\"V\n\x0b\x42otResponse\x12\r\n\x05\x62otId\x18\x01 \x01(\x04\x12 \n\x06status\x18\x02 \x01(\x0e\x32\x10.OperationStatus\x12\x16\n\x02op\x18\x03 \x01(\x0e\x32\n.Operation\"\x1b\n\nBotRequest\x12\r\n\x05\x62otId\x18\x01 \x01(\x04\"!\n\x0f\x42otsDataRequest\x12\x0e\n\x06userId\x18\x01 \x01(\x04*<\n\x0fOperationStatus\x12\x0e\n\nSUCCESSFUL\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\x12\r\n\tWRONG_BOT\x10\x02*\x9f\x01\n\tOperation\x12\x0e\n\nREMOVE_BOT\x10\x00\x12\x0e\n\nRESUME_BOT\x10\x01\x12\r\n\tPAUSE_BOT\x10\x02\x12\x0c\n\x08STOP_BOT\x10\x03\x12\x0e\n\nRENAME_BOT\x10\x04\x12\x16\n\x12UPDATE_DESCRIPTION\x10\x05\x12\x0f\n\x0bOPEN_TRADES\x10\x06\x12\x12\n\x0eTRADE_RESPONSE\x10\x07\x12\x08\n\x04PING\x10\x08\x62\x06proto3'
)

_OPERATIONSTATUS = _descriptor.EnumDescriptor(
  name='OperationStatus',
  full_name='OperationStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESSFUL', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FAILED', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WRONG_BOT', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=179,
  serialized_end=239,
)
_sym_db.RegisterEnumDescriptor(_OPERATIONSTATUS)

OperationStatus = enum_type_wrapper.EnumTypeWrapper(_OPERATIONSTATUS)
_OPERATION = _descriptor.EnumDescriptor(
  name='Operation',
  full_name='Operation',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='REMOVE_BOT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RESUME_BOT', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PAUSE_BOT', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STOP_BOT', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RENAME_BOT', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UPDATE_DESCRIPTION', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OPEN_TRADES', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TRADE_RESPONSE', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PING', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=242,
  serialized_end=401,
)
_sym_db.RegisterEnumDescriptor(_OPERATION)

Operation = enum_type_wrapper.EnumTypeWrapper(_OPERATION)
SUCCESSFUL = 0
FAILED = 1
WRONG_BOT = 2
REMOVE_BOT = 0
RESUME_BOT = 1
PAUSE_BOT = 2
STOP_BOT = 3
RENAME_BOT = 4
UPDATE_DESCRIPTION = 5
OPEN_TRADES = 6
TRADE_RESPONSE = 7
PING = 8



_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=25,
)


_BOTRESPONSE = _descriptor.Descriptor(
  name='BotResponse',
  full_name='BotResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='botId', full_name='BotResponse.botId', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='BotResponse.status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='op', full_name='BotResponse.op', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=113,
)


_BOTREQUEST = _descriptor.Descriptor(
  name='BotRequest',
  full_name='BotRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='botId', full_name='BotRequest.botId', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=142,
)


_BOTSDATAREQUEST = _descriptor.Descriptor(
  name='BotsDataRequest',
  full_name='BotsDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='BotsDataRequest.userId', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=177,
)

_BOTRESPONSE.fields_by_name['status'].enum_type = _OPERATIONSTATUS
_BOTRESPONSE.fields_by_name['op'].enum_type = _OPERATION
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['BotResponse'] = _BOTRESPONSE
DESCRIPTOR.message_types_by_name['BotRequest'] = _BOTREQUEST
DESCRIPTOR.message_types_by_name['BotsDataRequest'] = _BOTSDATAREQUEST
DESCRIPTOR.enum_types_by_name['OperationStatus'] = _OPERATIONSTATUS
DESCRIPTOR.enum_types_by_name['Operation'] = _OPERATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'bot_comm_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

BotResponse = _reflection.GeneratedProtocolMessageType('BotResponse', (_message.Message,), {
  'DESCRIPTOR' : _BOTRESPONSE,
  '__module__' : 'bot_comm_pb2'
  # @@protoc_insertion_point(class_scope:BotResponse)
  })
_sym_db.RegisterMessage(BotResponse)

BotRequest = _reflection.GeneratedProtocolMessageType('BotRequest', (_message.Message,), {
  'DESCRIPTOR' : _BOTREQUEST,
  '__module__' : 'bot_comm_pb2'
  # @@protoc_insertion_point(class_scope:BotRequest)
  })
_sym_db.RegisterMessage(BotRequest)

BotsDataRequest = _reflection.GeneratedProtocolMessageType('BotsDataRequest', (_message.Message,), {
  'DESCRIPTOR' : _BOTSDATAREQUEST,
  '__module__' : 'bot_comm_pb2'
  # @@protoc_insertion_point(class_scope:BotsDataRequest)
  })
_sym_db.RegisterMessage(BotsDataRequest)


# @@protoc_insertion_point(module_scope)
