# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import candle_data_service_pb2 as candle__data__service__pb2


class CandleDataServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLiveInfo = channel.unary_unary(
                '/candles.CandleDataService/GetLiveInfo',
                request_serializer=candle__data__service__pb2.LiveInfoRequest.SerializeToString,
                response_deserializer=candle__data__service__pb2.LiveInfoResponse.FromString,
                )
        self.GetCandles = channel.unary_unary(
                '/candles.CandleDataService/GetCandles',
                request_serializer=candle__data__service__pb2.CandlesRequest.SerializeToString,
                response_deserializer=candle__data__service__pb2.CandlesResponse.FromString,
                )


class CandleDataServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetLiveInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCandles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CandleDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLiveInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLiveInfo,
                    request_deserializer=candle__data__service__pb2.LiveInfoRequest.FromString,
                    response_serializer=candle__data__service__pb2.LiveInfoResponse.SerializeToString,
            ),
            'GetCandles': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCandles,
                    request_deserializer=candle__data__service__pb2.CandlesRequest.FromString,
                    response_serializer=candle__data__service__pb2.CandlesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'candles.CandleDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CandleDataService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetLiveInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/candles.CandleDataService/GetLiveInfo',
            candle__data__service__pb2.LiveInfoRequest.SerializeToString,
            candle__data__service__pb2.LiveInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCandles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/candles.CandleDataService/GetCandles',
            candle__data__service__pb2.CandlesRequest.SerializeToString,
            candle__data__service__pb2.CandlesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
