# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import candle_data_injector_pb2 as candle__data__injector__pb2


class CandleDataInjectorCommunicatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.subscribeCandles = channel.unary_unary(
                '/candles.CandleDataInjectorCommunicator/subscribeCandles',
                request_serializer=candle__data__injector__pb2.SubscribeCandlesRequest.SerializeToString,
                response_deserializer=candle__data__injector__pb2.SubscriptionResponse.FromString,
                )
        self.unsubscribeCandles = channel.unary_unary(
                '/candles.CandleDataInjectorCommunicator/unsubscribeCandles',
                request_serializer=candle__data__injector__pb2.SubscribeCandlesRequest.SerializeToString,
                response_deserializer=candle__data__injector__pb2.SubscriptionResponse.FromString,
                )


class CandleDataInjectorCommunicatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def subscribeCandles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def unsubscribeCandles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CandleDataInjectorCommunicatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'subscribeCandles': grpc.unary_unary_rpc_method_handler(
                    servicer.subscribeCandles,
                    request_deserializer=candle__data__injector__pb2.SubscribeCandlesRequest.FromString,
                    response_serializer=candle__data__injector__pb2.SubscriptionResponse.SerializeToString,
            ),
            'unsubscribeCandles': grpc.unary_unary_rpc_method_handler(
                    servicer.unsubscribeCandles,
                    request_deserializer=candle__data__injector__pb2.SubscribeCandlesRequest.FromString,
                    response_serializer=candle__data__injector__pb2.SubscriptionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'candles.CandleDataInjectorCommunicator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CandleDataInjectorCommunicator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def subscribeCandles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/candles.CandleDataInjectorCommunicator/subscribeCandles',
            candle__data__injector__pb2.SubscribeCandlesRequest.SerializeToString,
            candle__data__injector__pb2.SubscriptionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def unsubscribeCandles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/candles.CandleDataInjectorCommunicator/unsubscribeCandles',
            candle__data__injector__pb2.SubscribeCandlesRequest.SerializeToString,
            candle__data__injector__pb2.SubscriptionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
