# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: candle_data_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import candle_pb2 as candle__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='candle_data_service.proto',
  package='candles',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19\x63\x61ndle_data_service.proto\x12\x07\x63\x61ndles\x1a\x0c\x63\x61ndle.proto\"7\n\x0fLiveInfoRequest\x12\x15\n\rexchange_name\x18\x01 \x01(\t\x12\r\n\x05pairs\x18\x02 \x03(\t\"\x9c\x01\n\x10LiveInfoResponse\x12\x15\n\rexchange_name\x18\x01 \x01(\t\x12\x35\n\x05pairs\x18\x02 \x03(\x0b\x32&.candles.LiveInfoResponse.PairLiveInfo\x1a:\n\x0cPairLiveInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04last\x18\x02 \x01(\x01\x12\x0e\n\x06volume\x18\x03 \x01(\x01\"\xcf\x01\n\x0e\x43\x61ndlesRequest\x12\x15\n\rexchange_name\x18\x01 \x01(\t\x12\x15\n\rcurrency_pair\x18\x02 \x01(\t\x12\x13\n\x0b\x63\x61ndle_size\x18\x03 \x01(\t\x12\x1b\n\x0elast_n_candles\x18\x04 \x01(\x04H\x00\x88\x01\x01\x12\x17\n\ntime_start\x18\x05 \x01(\x04H\x01\x88\x01\x01\x12\x15\n\x08time_end\x18\x06 \x01(\x04H\x02\x88\x01\x01\x42\x11\n\x0f_last_n_candlesB\r\n\x0b_time_startB\x0b\n\t_time_end\"c\n\x0f\x43\x61ndlesResponse\x12\x15\n\rexchange_name\x18\x01 \x01(\t\x12\x13\n\x0b\x63\x61ndle_size\x18\x02 \x01(\t\x12$\n\x07\x63\x61ndles\x18\x03 \x03(\x0b\x32\x13.candles.CandleData2\x9c\x01\n\x11\x43\x61ndleDataService\x12\x44\n\x0bGetLiveInfo\x12\x18.candles.LiveInfoRequest\x1a\x19.candles.LiveInfoResponse\"\x00\x12\x41\n\nGetCandles\x12\x17.candles.CandlesRequest\x1a\x18.candles.CandlesResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[candle__pb2.DESCRIPTOR,])




_LIVEINFOREQUEST = _descriptor.Descriptor(
  name='LiveInfoRequest',
  full_name='candles.LiveInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='exchange_name', full_name='candles.LiveInfoRequest.exchange_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pairs', full_name='candles.LiveInfoRequest.pairs', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=107,
)


_LIVEINFORESPONSE_PAIRLIVEINFO = _descriptor.Descriptor(
  name='PairLiveInfo',
  full_name='candles.LiveInfoResponse.PairLiveInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='candles.LiveInfoResponse.PairLiveInfo.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last', full_name='candles.LiveInfoResponse.PairLiveInfo.last', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='volume', full_name='candles.LiveInfoResponse.PairLiveInfo.volume', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=208,
  serialized_end=266,
)

_LIVEINFORESPONSE = _descriptor.Descriptor(
  name='LiveInfoResponse',
  full_name='candles.LiveInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='exchange_name', full_name='candles.LiveInfoResponse.exchange_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pairs', full_name='candles.LiveInfoResponse.pairs', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_LIVEINFORESPONSE_PAIRLIVEINFO, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=266,
)


_CANDLESREQUEST = _descriptor.Descriptor(
  name='CandlesRequest',
  full_name='candles.CandlesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='exchange_name', full_name='candles.CandlesRequest.exchange_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='currency_pair', full_name='candles.CandlesRequest.currency_pair', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='candle_size', full_name='candles.CandlesRequest.candle_size', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_n_candles', full_name='candles.CandlesRequest.last_n_candles', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time_start', full_name='candles.CandlesRequest.time_start', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time_end', full_name='candles.CandlesRequest.time_end', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_last_n_candles', full_name='candles.CandlesRequest._last_n_candles',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_time_start', full_name='candles.CandlesRequest._time_start',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_time_end', full_name='candles.CandlesRequest._time_end',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=269,
  serialized_end=476,
)


_CANDLESRESPONSE = _descriptor.Descriptor(
  name='CandlesResponse',
  full_name='candles.CandlesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='exchange_name', full_name='candles.CandlesResponse.exchange_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='candle_size', full_name='candles.CandlesResponse.candle_size', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='candles', full_name='candles.CandlesResponse.candles', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=478,
  serialized_end=577,
)

_LIVEINFORESPONSE_PAIRLIVEINFO.containing_type = _LIVEINFORESPONSE
_LIVEINFORESPONSE.fields_by_name['pairs'].message_type = _LIVEINFORESPONSE_PAIRLIVEINFO
_CANDLESREQUEST.oneofs_by_name['_last_n_candles'].fields.append(
  _CANDLESREQUEST.fields_by_name['last_n_candles'])
_CANDLESREQUEST.fields_by_name['last_n_candles'].containing_oneof = _CANDLESREQUEST.oneofs_by_name['_last_n_candles']
_CANDLESREQUEST.oneofs_by_name['_time_start'].fields.append(
  _CANDLESREQUEST.fields_by_name['time_start'])
_CANDLESREQUEST.fields_by_name['time_start'].containing_oneof = _CANDLESREQUEST.oneofs_by_name['_time_start']
_CANDLESREQUEST.oneofs_by_name['_time_end'].fields.append(
  _CANDLESREQUEST.fields_by_name['time_end'])
_CANDLESREQUEST.fields_by_name['time_end'].containing_oneof = _CANDLESREQUEST.oneofs_by_name['_time_end']
_CANDLESRESPONSE.fields_by_name['candles'].message_type = candle__pb2._CANDLEDATA
DESCRIPTOR.message_types_by_name['LiveInfoRequest'] = _LIVEINFOREQUEST
DESCRIPTOR.message_types_by_name['LiveInfoResponse'] = _LIVEINFORESPONSE
DESCRIPTOR.message_types_by_name['CandlesRequest'] = _CANDLESREQUEST
DESCRIPTOR.message_types_by_name['CandlesResponse'] = _CANDLESRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LiveInfoRequest = _reflection.GeneratedProtocolMessageType('LiveInfoRequest', (_message.Message,), {
  'DESCRIPTOR' : _LIVEINFOREQUEST,
  '__module__' : 'candle_data_service_pb2'
  # @@protoc_insertion_point(class_scope:candles.LiveInfoRequest)
  })
_sym_db.RegisterMessage(LiveInfoRequest)

LiveInfoResponse = _reflection.GeneratedProtocolMessageType('LiveInfoResponse', (_message.Message,), {

  'PairLiveInfo' : _reflection.GeneratedProtocolMessageType('PairLiveInfo', (_message.Message,), {
    'DESCRIPTOR' : _LIVEINFORESPONSE_PAIRLIVEINFO,
    '__module__' : 'candle_data_service_pb2'
    # @@protoc_insertion_point(class_scope:candles.LiveInfoResponse.PairLiveInfo)
    })
  ,
  'DESCRIPTOR' : _LIVEINFORESPONSE,
  '__module__' : 'candle_data_service_pb2'
  # @@protoc_insertion_point(class_scope:candles.LiveInfoResponse)
  })
_sym_db.RegisterMessage(LiveInfoResponse)
_sym_db.RegisterMessage(LiveInfoResponse.PairLiveInfo)

CandlesRequest = _reflection.GeneratedProtocolMessageType('CandlesRequest', (_message.Message,), {
  'DESCRIPTOR' : _CANDLESREQUEST,
  '__module__' : 'candle_data_service_pb2'
  # @@protoc_insertion_point(class_scope:candles.CandlesRequest)
  })
_sym_db.RegisterMessage(CandlesRequest)

CandlesResponse = _reflection.GeneratedProtocolMessageType('CandlesResponse', (_message.Message,), {
  'DESCRIPTOR' : _CANDLESRESPONSE,
  '__module__' : 'candle_data_service_pb2'
  # @@protoc_insertion_point(class_scope:candles.CandlesResponse)
  })
_sym_db.RegisterMessage(CandlesResponse)



_CANDLEDATASERVICE = _descriptor.ServiceDescriptor(
  name='CandleDataService',
  full_name='candles.CandleDataService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=580,
  serialized_end=736,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetLiveInfo',
    full_name='candles.CandleDataService.GetLiveInfo',
    index=0,
    containing_service=None,
    input_type=_LIVEINFOREQUEST,
    output_type=_LIVEINFORESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetCandles',
    full_name='candles.CandleDataService.GetCandles',
    index=1,
    containing_service=None,
    input_type=_CANDLESREQUEST,
    output_type=_CANDLESRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CANDLEDATASERVICE)

DESCRIPTOR.services_by_name['CandleDataService'] = _CANDLEDATASERVICE

# @@protoc_insertion_point(module_scope)
