# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: candle_data_injector.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='candle_data_injector.proto',
  package='candles',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1a\x63\x61ndle_data_injector.proto\x12\x07\x63\x61ndles\"\xa6\x01\n\x17SubscribeCandlesRequest\x12\x15\n\rexchange_name\x18\x01 \x01(\t\x12\x43\n\x07\x63\x61ndles\x18\x02 \x03(\x0b\x32\x32.candles.SubscribeCandlesRequest.CandleSizeSetting\x1a/\n\x11\x43\x61ndleSizeSetting\x12\x0c\n\x04size\x18\x01 \x01(\t\x12\x0c\n\x04pair\x18\x02 \x03(\t\"m\n\x14SubscriptionResponse\x12\x34\n\x06status\x18\x01 \x01(\x0e\x32$.candles.SubscriptionResponse.Status\"\x1f\n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\x08\n\x04\x46\x41IL\x10\x01\x32\xd0\x01\n\x1e\x43\x61ndleDataInjectorCommunicator\x12U\n\x10subscribeCandles\x12 .candles.SubscribeCandlesRequest\x1a\x1d.candles.SubscriptionResponse\"\x00\x12W\n\x12unsubscribeCandles\x12 .candles.SubscribeCandlesRequest\x1a\x1d.candles.SubscriptionResponse\"\x00\x62\x06proto3'
)



_SUBSCRIPTIONRESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='candles.SubscriptionResponse.Status',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FAIL', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=286,
  serialized_end=317,
)
_sym_db.RegisterEnumDescriptor(_SUBSCRIPTIONRESPONSE_STATUS)


_SUBSCRIBECANDLESREQUEST_CANDLESIZESETTING = _descriptor.Descriptor(
  name='CandleSizeSetting',
  full_name='candles.SubscribeCandlesRequest.CandleSizeSetting',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='size', full_name='candles.SubscribeCandlesRequest.CandleSizeSetting.size', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pair', full_name='candles.SubscribeCandlesRequest.CandleSizeSetting.pair', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=206,
)

_SUBSCRIBECANDLESREQUEST = _descriptor.Descriptor(
  name='SubscribeCandlesRequest',
  full_name='candles.SubscribeCandlesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='exchange_name', full_name='candles.SubscribeCandlesRequest.exchange_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='candles', full_name='candles.SubscribeCandlesRequest.candles', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SUBSCRIBECANDLESREQUEST_CANDLESIZESETTING, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=206,
)


_SUBSCRIPTIONRESPONSE = _descriptor.Descriptor(
  name='SubscriptionResponse',
  full_name='candles.SubscriptionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='candles.SubscriptionResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SUBSCRIPTIONRESPONSE_STATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=208,
  serialized_end=317,
)

_SUBSCRIBECANDLESREQUEST_CANDLESIZESETTING.containing_type = _SUBSCRIBECANDLESREQUEST
_SUBSCRIBECANDLESREQUEST.fields_by_name['candles'].message_type = _SUBSCRIBECANDLESREQUEST_CANDLESIZESETTING
_SUBSCRIPTIONRESPONSE.fields_by_name['status'].enum_type = _SUBSCRIPTIONRESPONSE_STATUS
_SUBSCRIPTIONRESPONSE_STATUS.containing_type = _SUBSCRIPTIONRESPONSE
DESCRIPTOR.message_types_by_name['SubscribeCandlesRequest'] = _SUBSCRIBECANDLESREQUEST
DESCRIPTOR.message_types_by_name['SubscriptionResponse'] = _SUBSCRIPTIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SubscribeCandlesRequest = _reflection.GeneratedProtocolMessageType('SubscribeCandlesRequest', (_message.Message,), {

  'CandleSizeSetting' : _reflection.GeneratedProtocolMessageType('CandleSizeSetting', (_message.Message,), {
    'DESCRIPTOR' : _SUBSCRIBECANDLESREQUEST_CANDLESIZESETTING,
    '__module__' : 'candle_data_injector_pb2'
    # @@protoc_insertion_point(class_scope:candles.SubscribeCandlesRequest.CandleSizeSetting)
    })
  ,
  'DESCRIPTOR' : _SUBSCRIBECANDLESREQUEST,
  '__module__' : 'candle_data_injector_pb2'
  # @@protoc_insertion_point(class_scope:candles.SubscribeCandlesRequest)
  })
_sym_db.RegisterMessage(SubscribeCandlesRequest)
_sym_db.RegisterMessage(SubscribeCandlesRequest.CandleSizeSetting)

SubscriptionResponse = _reflection.GeneratedProtocolMessageType('SubscriptionResponse', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIPTIONRESPONSE,
  '__module__' : 'candle_data_injector_pb2'
  # @@protoc_insertion_point(class_scope:candles.SubscriptionResponse)
  })
_sym_db.RegisterMessage(SubscriptionResponse)



_CANDLEDATAINJECTORCOMMUNICATOR = _descriptor.ServiceDescriptor(
  name='CandleDataInjectorCommunicator',
  full_name='candles.CandleDataInjectorCommunicator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=320,
  serialized_end=528,
  methods=[
  _descriptor.MethodDescriptor(
    name='subscribeCandles',
    full_name='candles.CandleDataInjectorCommunicator.subscribeCandles',
    index=0,
    containing_service=None,
    input_type=_SUBSCRIBECANDLESREQUEST,
    output_type=_SUBSCRIPTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='unsubscribeCandles',
    full_name='candles.CandleDataInjectorCommunicator.unsubscribeCandles',
    index=1,
    containing_service=None,
    input_type=_SUBSCRIBECANDLESREQUEST,
    output_type=_SUBSCRIPTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CANDLEDATAINJECTORCOMMUNICATOR)

DESCRIPTOR.services_by_name['CandleDataInjectorCommunicator'] = _CANDLEDATAINJECTORCOMMUNICATOR

# @@protoc_insertion_point(module_scope)
