# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: statistics.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import transaction_pb2 as transaction__pb2
import bot_comm_pb2 as bot__comm__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='statistics.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10statistics.proto\x1a\x11transaction.proto\x1a\x0e\x62ot_comm.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"^\n\rBotStatistics\x12\r\n\x05\x62otId\x18\x01 \x01(\x04\x12\x0e\n\x06profit\x18\x02 \x01(\x01\x12\x16\n\x06\x61ssets\x18\x03 \x03(\x0b\x32\x06.Asset\x12\x16\n\x0esinceLastTrade\x18\x04 \x01(\x05\"`\n\x05\x41sset\x12\x0c\n\x04pair\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\x12\x13\n\x0b\x63urrentRate\x18\x03 \x01(\x01\x12\x14\n\x0c\x63urrentValue\x18\x04 \x01(\x01\x12\x0e\n\x06profit\x18\x05 \x01(\x02\"1\n\x08\x42otAsset\x12\r\n\x05\x62otId\x18\x01 \x01(\x04\x12\x16\n\x06\x61ssets\x18\x02 \x03(\x0b\x32\x06.Asset\"\'\n\nUserAssets\x12\x19\n\x06\x61ssets\x18\x01 \x03(\x0b\x32\t.BotAsset\"\xab\x01\n\x11OverallStatistics\x12\x13\n\x0btotalProfit\x18\x01 \x01(\x01\x12\x14\n\x0ctotalBalance\x18\x02 \x01(\x01\x12\x15\n\rlastTradeTime\x18\x03 \x01(\t\x12\x13\n\x0b\x62\x65stBotName\x18\x04 \x01(\t\x12\x14\n\x0cworstBotName\x18\x05 \x01(\t\x12\x16\n\x0erealisedTrades\x18\x06 \x01(\x05\x12\x11\n\tallTrades\x18\x07 \x01(\x05\x32\xc9\x02\n\x1dStatisticsServiceCommunicator\x12\x43\n\x16GetAllUserTransactions\x12\x10.BotsDataRequest\x1a\x15.TransactionsExtended\"\x00\x12:\n\x12GetBotTransactions\x12\x0b.BotRequest\x1a\x15.TransactionsExtended\"\x00\x12\x31\n\x10GetBotStatistics\x12\x0b.BotRequest\x1a\x0e.BotStatistics\"\x00\x12\x42\n\x18GetBotsOverallStatistics\x12\x10.BotsDataRequest\x1a\x12.OverallStatistics\"\x00\x12\x30\n\rGetUserAssets\x12\x10.BotsDataRequest\x1a\x0b.UserAssets\"\x00\x62\x06proto3'
  ,
  dependencies=[transaction__pb2.DESCRIPTOR,bot__comm__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_BOTSTATISTICS = _descriptor.Descriptor(
  name='BotStatistics',
  full_name='BotStatistics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='botId', full_name='BotStatistics.botId', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='profit', full_name='BotStatistics.profit', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='assets', full_name='BotStatistics.assets', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sinceLastTrade', full_name='BotStatistics.sinceLastTrade', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=182,
)


_ASSET = _descriptor.Descriptor(
  name='Asset',
  full_name='Asset',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pair', full_name='Asset.pair', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='amount', full_name='Asset.amount', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='currentRate', full_name='Asset.currentRate', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='currentValue', full_name='Asset.currentValue', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='profit', full_name='Asset.profit', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=280,
)


_BOTASSET = _descriptor.Descriptor(
  name='BotAsset',
  full_name='BotAsset',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='botId', full_name='BotAsset.botId', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='assets', full_name='BotAsset.assets', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=282,
  serialized_end=331,
)


_USERASSETS = _descriptor.Descriptor(
  name='UserAssets',
  full_name='UserAssets',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='assets', full_name='UserAssets.assets', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=333,
  serialized_end=372,
)


_OVERALLSTATISTICS = _descriptor.Descriptor(
  name='OverallStatistics',
  full_name='OverallStatistics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='totalProfit', full_name='OverallStatistics.totalProfit', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='totalBalance', full_name='OverallStatistics.totalBalance', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lastTradeTime', full_name='OverallStatistics.lastTradeTime', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bestBotName', full_name='OverallStatistics.bestBotName', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='worstBotName', full_name='OverallStatistics.worstBotName', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='realisedTrades', full_name='OverallStatistics.realisedTrades', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='allTrades', full_name='OverallStatistics.allTrades', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=375,
  serialized_end=546,
)

_BOTSTATISTICS.fields_by_name['assets'].message_type = _ASSET
_BOTASSET.fields_by_name['assets'].message_type = _ASSET
_USERASSETS.fields_by_name['assets'].message_type = _BOTASSET
DESCRIPTOR.message_types_by_name['BotStatistics'] = _BOTSTATISTICS
DESCRIPTOR.message_types_by_name['Asset'] = _ASSET
DESCRIPTOR.message_types_by_name['BotAsset'] = _BOTASSET
DESCRIPTOR.message_types_by_name['UserAssets'] = _USERASSETS
DESCRIPTOR.message_types_by_name['OverallStatistics'] = _OVERALLSTATISTICS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BotStatistics = _reflection.GeneratedProtocolMessageType('BotStatistics', (_message.Message,), {
  'DESCRIPTOR' : _BOTSTATISTICS,
  '__module__' : 'statistics_pb2'
  # @@protoc_insertion_point(class_scope:BotStatistics)
  })
_sym_db.RegisterMessage(BotStatistics)

Asset = _reflection.GeneratedProtocolMessageType('Asset', (_message.Message,), {
  'DESCRIPTOR' : _ASSET,
  '__module__' : 'statistics_pb2'
  # @@protoc_insertion_point(class_scope:Asset)
  })
_sym_db.RegisterMessage(Asset)

BotAsset = _reflection.GeneratedProtocolMessageType('BotAsset', (_message.Message,), {
  'DESCRIPTOR' : _BOTASSET,
  '__module__' : 'statistics_pb2'
  # @@protoc_insertion_point(class_scope:BotAsset)
  })
_sym_db.RegisterMessage(BotAsset)

UserAssets = _reflection.GeneratedProtocolMessageType('UserAssets', (_message.Message,), {
  'DESCRIPTOR' : _USERASSETS,
  '__module__' : 'statistics_pb2'
  # @@protoc_insertion_point(class_scope:UserAssets)
  })
_sym_db.RegisterMessage(UserAssets)

OverallStatistics = _reflection.GeneratedProtocolMessageType('OverallStatistics', (_message.Message,), {
  'DESCRIPTOR' : _OVERALLSTATISTICS,
  '__module__' : 'statistics_pb2'
  # @@protoc_insertion_point(class_scope:OverallStatistics)
  })
_sym_db.RegisterMessage(OverallStatistics)



_STATISTICSSERVICECOMMUNICATOR = _descriptor.ServiceDescriptor(
  name='StatisticsServiceCommunicator',
  full_name='StatisticsServiceCommunicator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=549,
  serialized_end=878,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetAllUserTransactions',
    full_name='StatisticsServiceCommunicator.GetAllUserTransactions',
    index=0,
    containing_service=None,
    input_type=bot__comm__pb2._BOTSDATAREQUEST,
    output_type=transaction__pb2._TRANSACTIONSEXTENDED,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetBotTransactions',
    full_name='StatisticsServiceCommunicator.GetBotTransactions',
    index=1,
    containing_service=None,
    input_type=bot__comm__pb2._BOTREQUEST,
    output_type=transaction__pb2._TRANSACTIONSEXTENDED,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetBotStatistics',
    full_name='StatisticsServiceCommunicator.GetBotStatistics',
    index=2,
    containing_service=None,
    input_type=bot__comm__pb2._BOTREQUEST,
    output_type=_BOTSTATISTICS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetBotsOverallStatistics',
    full_name='StatisticsServiceCommunicator.GetBotsOverallStatistics',
    index=3,
    containing_service=None,
    input_type=bot__comm__pb2._BOTSDATAREQUEST,
    output_type=_OVERALLSTATISTICS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetUserAssets',
    full_name='StatisticsServiceCommunicator.GetUserAssets',
    index=4,
    containing_service=None,
    input_type=bot__comm__pb2._BOTSDATAREQUEST,
    output_type=_USERASSETS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_STATISTICSSERVICECOMMUNICATOR)

DESCRIPTOR.services_by_name['StatisticsServiceCommunicator'] = _STATISTICSSERVICECOMMUNICATOR

# @@protoc_insertion_point(module_scope)
