# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stock.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='stock.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bstock.proto\" \n\x0e\x46ortuneRequest\x12\x0e\n\x06userId\x18\x01 \x01(\x04\"*\n\x07\x46ortune\x12\x0e\n\x06userId\x18\x01 \x01(\x04\x12\x0f\n\x07\x66ortune\x18\x02 \x01(\x01\"\x8e\x01\n\x10StockTransaction\x12\x0e\n\x06userId\x18\x01 \x01(\x04\x12#\n\x04type\x18\x02 \x01(\x0e\x32\x15.StockTransactionType\x12\x14\n\x0c\x63urrencyPair\x18\x03 \x01(\t\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x01\x12\r\n\x05price\x18\x05 \x01(\x01\x12\x10\n\x08\x65xchange\x18\x06 \x01(\t\";\n\x12TransactionRequest\x12\x0e\n\x06userId\x18\x01 \x01(\x04\x12\x15\n\rtransactionId\x18\x02 \x01(\x04\"h\n\x14TransactionAckStatus\x12\x1a\n\rtransactionId\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12\"\n\x06status\x18\x02 \x01(\x0e\x32\x12.TransactionStatusB\x10\n\x0e_transactionId*)\n\x14StockTransactionType\x12\x07\n\x03\x42UY\x10\x00\x12\x08\n\x04SELL\x10\x01*L\n\x11TransactionStatus\x12\x0c\n\x08\x41\x43\x43\x45PTED\x10\x00\x12\x0c\n\x08REJECTED\x10\x01\x12\x0c\n\x08REALISED\x10\x02\x12\r\n\tCANCELLED\x10\x03\x32\xab\x02\n\x11StockCommunicator\x12\"\n\nAddFortune\x12\x08.Fortune\x1a\x08.Fortune\"\x00\x12)\n\nGetFortune\x12\x0f.FortuneRequest\x1a\x08.Fortune\"\x00\x12<\n\x0e\x41\x64\x64Transaction\x12\x11.StockTransaction\x1a\x15.TransactionAckStatus\"\x00\x12\x41\n\x11\x43\x61ncelTransaction\x12\x13.TransactionRequest\x1a\x15.TransactionAckStatus\"\x00\x12\x46\n\x16\x43heckTransactionStatus\x12\x13.TransactionRequest\x1a\x15.TransactionAckStatus\"\x00\x62\x06proto3'
)

_STOCKTRANSACTIONTYPE = _descriptor.EnumDescriptor(
  name='StockTransactionType',
  full_name='StockTransactionType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BUY', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SELL', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=405,
  serialized_end=446,
)
_sym_db.RegisterEnumDescriptor(_STOCKTRANSACTIONTYPE)

StockTransactionType = enum_type_wrapper.EnumTypeWrapper(_STOCKTRANSACTIONTYPE)
_TRANSACTIONSTATUS = _descriptor.EnumDescriptor(
  name='TransactionStatus',
  full_name='TransactionStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ACCEPTED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REJECTED', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REALISED', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CANCELLED', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=448,
  serialized_end=524,
)
_sym_db.RegisterEnumDescriptor(_TRANSACTIONSTATUS)

TransactionStatus = enum_type_wrapper.EnumTypeWrapper(_TRANSACTIONSTATUS)
BUY = 0
SELL = 1
ACCEPTED = 0
REJECTED = 1
REALISED = 2
CANCELLED = 3



_FORTUNEREQUEST = _descriptor.Descriptor(
  name='FortuneRequest',
  full_name='FortuneRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='FortuneRequest.userId', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=47,
)


_FORTUNE = _descriptor.Descriptor(
  name='Fortune',
  full_name='Fortune',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='Fortune.userId', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fortune', full_name='Fortune.fortune', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=91,
)


_STOCKTRANSACTION = _descriptor.Descriptor(
  name='StockTransaction',
  full_name='StockTransaction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='StockTransaction.userId', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='StockTransaction.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='currencyPair', full_name='StockTransaction.currencyPair', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='amount', full_name='StockTransaction.amount', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='price', full_name='StockTransaction.price', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='exchange', full_name='StockTransaction.exchange', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=236,
)


_TRANSACTIONREQUEST = _descriptor.Descriptor(
  name='TransactionRequest',
  full_name='TransactionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='TransactionRequest.userId', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transactionId', full_name='TransactionRequest.transactionId', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=238,
  serialized_end=297,
)


_TRANSACTIONACKSTATUS = _descriptor.Descriptor(
  name='TransactionAckStatus',
  full_name='TransactionAckStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='transactionId', full_name='TransactionAckStatus.transactionId', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='TransactionAckStatus.status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_transactionId', full_name='TransactionAckStatus._transactionId',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=299,
  serialized_end=403,
)

_STOCKTRANSACTION.fields_by_name['type'].enum_type = _STOCKTRANSACTIONTYPE
_TRANSACTIONACKSTATUS.fields_by_name['status'].enum_type = _TRANSACTIONSTATUS
_TRANSACTIONACKSTATUS.oneofs_by_name['_transactionId'].fields.append(
  _TRANSACTIONACKSTATUS.fields_by_name['transactionId'])
_TRANSACTIONACKSTATUS.fields_by_name['transactionId'].containing_oneof = _TRANSACTIONACKSTATUS.oneofs_by_name['_transactionId']
DESCRIPTOR.message_types_by_name['FortuneRequest'] = _FORTUNEREQUEST
DESCRIPTOR.message_types_by_name['Fortune'] = _FORTUNE
DESCRIPTOR.message_types_by_name['StockTransaction'] = _STOCKTRANSACTION
DESCRIPTOR.message_types_by_name['TransactionRequest'] = _TRANSACTIONREQUEST
DESCRIPTOR.message_types_by_name['TransactionAckStatus'] = _TRANSACTIONACKSTATUS
DESCRIPTOR.enum_types_by_name['StockTransactionType'] = _STOCKTRANSACTIONTYPE
DESCRIPTOR.enum_types_by_name['TransactionStatus'] = _TRANSACTIONSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FortuneRequest = _reflection.GeneratedProtocolMessageType('FortuneRequest', (_message.Message,), {
  'DESCRIPTOR' : _FORTUNEREQUEST,
  '__module__' : 'stock_pb2'
  # @@protoc_insertion_point(class_scope:FortuneRequest)
  })
_sym_db.RegisterMessage(FortuneRequest)

Fortune = _reflection.GeneratedProtocolMessageType('Fortune', (_message.Message,), {
  'DESCRIPTOR' : _FORTUNE,
  '__module__' : 'stock_pb2'
  # @@protoc_insertion_point(class_scope:Fortune)
  })
_sym_db.RegisterMessage(Fortune)

StockTransaction = _reflection.GeneratedProtocolMessageType('StockTransaction', (_message.Message,), {
  'DESCRIPTOR' : _STOCKTRANSACTION,
  '__module__' : 'stock_pb2'
  # @@protoc_insertion_point(class_scope:StockTransaction)
  })
_sym_db.RegisterMessage(StockTransaction)

TransactionRequest = _reflection.GeneratedProtocolMessageType('TransactionRequest', (_message.Message,), {
  'DESCRIPTOR' : _TRANSACTIONREQUEST,
  '__module__' : 'stock_pb2'
  # @@protoc_insertion_point(class_scope:TransactionRequest)
  })
_sym_db.RegisterMessage(TransactionRequest)

TransactionAckStatus = _reflection.GeneratedProtocolMessageType('TransactionAckStatus', (_message.Message,), {
  'DESCRIPTOR' : _TRANSACTIONACKSTATUS,
  '__module__' : 'stock_pb2'
  # @@protoc_insertion_point(class_scope:TransactionAckStatus)
  })
_sym_db.RegisterMessage(TransactionAckStatus)



_STOCKCOMMUNICATOR = _descriptor.ServiceDescriptor(
  name='StockCommunicator',
  full_name='StockCommunicator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=527,
  serialized_end=826,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddFortune',
    full_name='StockCommunicator.AddFortune',
    index=0,
    containing_service=None,
    input_type=_FORTUNE,
    output_type=_FORTUNE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetFortune',
    full_name='StockCommunicator.GetFortune',
    index=1,
    containing_service=None,
    input_type=_FORTUNEREQUEST,
    output_type=_FORTUNE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='AddTransaction',
    full_name='StockCommunicator.AddTransaction',
    index=2,
    containing_service=None,
    input_type=_STOCKTRANSACTION,
    output_type=_TRANSACTIONACKSTATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CancelTransaction',
    full_name='StockCommunicator.CancelTransaction',
    index=3,
    containing_service=None,
    input_type=_TRANSACTIONREQUEST,
    output_type=_TRANSACTIONACKSTATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CheckTransactionStatus',
    full_name='StockCommunicator.CheckTransactionStatus',
    index=4,
    containing_service=None,
    input_type=_TRANSACTIONREQUEST,
    output_type=_TRANSACTIONACKSTATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_STOCKCOMMUNICATOR)

DESCRIPTOR.services_by_name['StockCommunicator'] = _STOCKCOMMUNICATOR

# @@protoc_insertion_point(module_scope)
